 update book set   	METADATA_COMPLETE  = add_months(METADATA_COMPLETE  , 12*2000) where to_char( 	METADATA_COMPLETE , 'yyyy/mm/dd') < '16/05/27';end
update book set  SCAN_METADATA_COMPLETE  = add_months(SCAN_METADATA_COMPLETE  , 12*2000) where to_char(SCAN_METADATA_COMPLETE , 'yyyy/mm/dd') < '16/05/27';end
update book set  SCAN_START_DATE  = add_months(SCAN_START_DATE  , 12*2000) where to_char(SCAN_START_DATE , 'yyyy/mm/dd') < '16/05/27';end
update book set  SCAN_COMPLETE_DATE  = add_months(SCAN_COMPLETE_DATE  , 12*2000) where to_char(SCAN_COMPLETE_DATE , 'yyyy/mm/dd') < '16/05/27';end
update book set  SCAN_IA_START_DATE  = add_months(SCAN_IA_START_DATE  , 12*2000) where to_char(SCAN_IA_START_DATE , 'yyyy/mm/dd') < '16/05/27';end
update book set  SCAN_IA_COMPLETE_DATE  = add_months(SCAN_IA_COMPLETE_DATE  , 12*2000) where to_char(SCAN_IA_COMPLETE_DATE , 'yyyy/mm/dd') < '16/05/27';end
update book set  FILES_SENT_TO_OREM  = add_months(FILES_SENT_TO_OREM  , 12*2000) where to_char(FILES_SENT_TO_OREM , 'yyyy/mm/dd') < '16/05/27';end
update book set FILES_RECEIVED_BY_OREM  = add_months(FILES_RECEIVED_BY_OREM , 12*2000) where to_char(FILES_RECEIVED_BY_OREM , 'yyyy/mm/dd') < '16/05/27';end
update book set  IA_START_DATE  = add_months(IA_START_DATE  , 12*2000) where to_char(IA_START_DATE , 'yyyy/mm/dd') < '16/05/27';end
update book set  IA_COMPLETE_DATE  = add_months(IA_COMPLETE_DATE  , 12*2000) where to_char(IA_COMPLETE_DATE , 'yyyy/mm/dd') < '16/05/27';end
update book set  OCR_COMPLETE_DATE  = add_months(OCR_COMPLETE_DATE  , 12*2000) where to_char(OCR_COMPLETE_DATE , 'yyyy/mm/dd') < '16/05/27';end
update book set PDFREVIEW_START_DATE  = add_months(PDFREVIEW_START_DATE  , 12*2000) where to_char(PDFREVIEW_START_DATE , 'yyyy/mm/dd') < '16/05/27';end
update book set PDF_READY  = add_months(PDF_READY , 12*2000) where to_char( PDF_READY , 'yyyy/mm/dd') < '16/05/27';end
update book set DATE_RELEASED  = add_months(DATE_RELEASED  , 12*2000) where to_char(DATE_RELEASED , 'yyyy/mm/dd') < '16/05/27';end
update book set DATE_LOADED = add_months( DATE_LOADED , 12*2000) where to_char(DATE_LOADED , 'yyyy/mm/dd') < '16/05/27';end
update book set PDF_OREM_ARCHIVED_DATE = add_months(PDF_OREM_ARCHIVED_DATE , 12*2000) where to_char(PDF_OREM_ARCHIVED_DATE , 'yyyy/mm/dd') < '16/05/27';end
update book set PDF_COPY2_ARCHIVED_DATE  = add_months(PDF_COPY2_ARCHIVED_DATE  , 12*2000) where to_char(PDF_COPY2_ARCHIVED_DATE , 'yyyy/mm/dd') < '16/05/27';end
update book set TIFF_OREM_ARCHIVED_DATE  = add_months(TIFF_OREM_ARCHIVED_DATE  , 12*2000) where to_char(TIFF_OREM_ARCHIVED_DATE, 'yyyy/mm/dd') < '16/05/27';end
update book set TIFF_COPY2_ARCHIVED_DATE  = add_months(TIFF_COPY2_ARCHIVED_DATE  , 12*2000) where to_char(TIFF_COPY2_ARCHIVED_DATE , 'yyyy/mm/dd') < '16/05/27';end
update book set PDF_SENT_TO_LOAD  = add_months(PDF_SENT_TO_LOAD  , 12*2000) where to_char(PDF_SENT_TO_LOAD , 'yyyy/mm/dd') < '16/05/27';end
update book set DATE_ORIGINAL = add_months(DATE_ORIGINAL , 12*2000) where to_char(DATE_ORIGINAL , 'yyyy/mm/dd') < '16/05/27';end
update book set PDF_DOWNLOAD_DATE = add_months(PDF_DOWNLOAD_DATE , 12*2000) where to_char(PDF_DOWNLOAD_DATE, 'yyyy/mm/dd') < '16/05/27';end
update book set OCR_START_DATE = add_months(OCR_START_DATE , 12*2000) where to_char(OCR_START_DATE , 'yyyy/mm/dd') < '16/05/27';end
update book set DATE_REPUBLISHED = add_months(DATE_REPUBLISHED , 12*2000) where to_char(DATE_REPUBLISHED , 'yyyy/mm/dd') < '16/05/27';end
update book set PULL_DATE = add_months(PULL_DATE , 12*2000) where to_char(PULL_DATE , 'yyyy/mm/dd') < '16/05/27';end